### ISSUE TITLE
USART hangs on read overrun

### ISSUE THREAD

**Issue by ctz** [leaflabs/libmaple#107]
I have a program which alternately communicates on uart1 and bit-bangs GPIO to talk a certain protocol. When doing the bit-banging, interrupts are turned off.

This hangs very occasionally (~once an hour) on maple mini.

I attached a debugger and caught the hang in action: it's an interrupt flood to USART1 because `usart_irq` doesn't handle all the exceptions it enables.

The datasheet says:

> Bit 3 ORE: Overrun error
> This bit is set by hardware when the word currently being received in the shift register is
> ready to be transferred into the RDR register while RXNE=1. **An interrupt is generated if
> RXNEIE=1 in the USART_CR1 register. It is cleared by a software sequence (an read to the
> USART_SR register followed by a read to the USART_DR register).**

So while the current code will read DR and therefore clear RXNE, it never reads SR to clear ORE.  If there is an overrun it will never clear that exception and it will be continually reasserted forever. This is the cause of the hang I saw.

(Obviously this means I'm losing bytes sometimes, and that's fine for my application. YMMV, which is why this is an issue and not a pull request.)

**Comment by ctz** [comment]
https://gist.github.com/ctz/86b63fa8d95b42d04245

Patch which Works For Me™

**Comment by mbolivar** [comment]
Thanks for this! Mind submitting a PR?

**Comment by madias123** [comment]
ctz: How about join the new STM32-arduino community: http://stm32duino.com/ ?

**Comment by bnewbold** [comment]
@mbolivar patch was merged, so this ticket should be closed now

**Comment by mbolivar** [comment]
done, thanks
