### ISSUE TITLE
Documentation down?

### ISSUE THREAD

**Issue by Gregwar** [leaflabs/libmaple#114]
Hello,

It looks like the doc is down:
http://leaflabs.com/docs/hardware/maple-mini.html

Apparently, static.leaflabs.com does not resolve anymore
Any idea?

**Comment by mbolivar** [comment]
Please refer to the following news notices:

http://www.leaflabs.com/news/2015/3/27/maple-end-of-life-notice
http://www.leaflabs.com/news/2016/1/22/maple-wiki-docs
