### ISSUE TITLE
PWM not working on pin 9?

### ISSUE THREAD

**Issue by Gregwar** [leaflabs/libmaple#117]
It appear that pin 9 PWM doesn't work, the following code:

```c++
    HardwareTimer timer(2);
    timer.pause();
    timer.setCount(0);
    timer.setOverflow(1000);
    timer.setPrescaleFactor(1);
    timer.setMode(TIMER_CH1, TIMER_PWM);
    timer.setMode(TIMER_CH2, TIMER_PWM);
    timer.setMode(TIMER_CH3, TIMER_PWM);
    timer.setMode(TIMER_CH4, TIMER_PWM);
    timer.refresh();
    timer.resume();

    pinMode(9, PWM);
    pwmWrite(9, 500);
```

Doesn't produce a PWM output on pin 9
However, writing it using OUTPUT and digitalWrite works
Also, producing a PWM on pin 8, which is also on timer 2 works

Any idea? (I've tried on two different boards just in case)

**Comment by mbolivar** [comment]
No idea, sorry. We'd gratefully take a patch, but since Maple is EOL won't be working on issues.

**Comment by Gregwar** [comment]
OK
Do you have the setup to confirm or disconfirm the issue?
No problem if you can't, I will investigate
Thank you

**Comment by Gregwar** [comment]
It actually appear that this is related to my bootloader (still not sure why)
